[package]
name = "from_underground"
version = "0.1.0"
authors = ["runner"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1.10"
rand = "0.8.5"
dialoguer = "*"
ansi_term = "*"